services:
  - type: web
    name: smart-mart
    runtime: python
    buildCommand: pip install -r requirements.txt && bash build.sh
    startCommand: gunicorn "smart_mart.app:create_app('production')" --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
